### PR TITLE
Update Getting Start Ruby SDK to be compatible with 3.0

### PR DESCRIPTION
**Pull request by jacobxcodes**
# Summary
This PR enables `ruby 3.0` compatibility.
 
## Changes

- added `thin gem at 1.8.1`
- updated variables to global syntax. Converted  `@@ > $`
- updated README with small change

Asana: https://app.asana.com/0/1203898735752010/1204091562765652

### CODE REVIEW

**Review by s-ashwinkumar — COMMENTED** [review]
This looks good to me, but i do have a question. The .`.ruby-version` in the root directory and in the `app` directory mention ruby 2.7.0. For me that actually results in a warning message like this : 

image


So question is should we delete this or just update the version number there to 3.x or something ?

**Comment by jacobxcodes** [comment]
@s-ashwinkumar that's a good question. Is there a way to specify more than one version or a greater than or equal to this version? I'm not familiar with the syntax and how that file is read.

**Comment by s-ashwinkumar** [comment]
> @s-ashwinkumar that's a good question. Is there a way to specify more than one version or a greater than or equal to this version? I'm not familiar with the syntax and how that file is read.

Yea, i was looking into it, apparently no way. Lets just leave it there then ? I might add a commit to this to handle the dependabot PRs (updating dependencies)

**Review by s-ashwinkumar — APPROVED** [review]
🚢

**Pull request merged**
